### ISSUE TITLE
bug: respect tree-shaking

### ISSUE THREAD

**Issue by jeetiss** [privatenumber/pkg-size.dev#10]
tree-shaking doesn't work for some reason, so it is impossible to test anything

size of `hexToString` from `viem` package with pkg-size is `87KB`, but it is wrong
https://pkg-size.dev/viem

<details>
    <summary>👉🏻 snapshot</summary>

<img width="1124" alt="Снимок экрана 2023-07-19 в 19 52 07" src="https://github.com/privatenumber/pkg-size.dev/assets/6726016/dc9df8c3-1ab8-4999-892d-2c2897202e14">

</details>

size of `hexToString` from `viem` package with bundlejs is `3.63 kB`, and it is close to true
https://bundlejs.com/?q=viem&treeshake=%5B%7BhexToString%7D%5D

<details>
    <summary>👉🏻 snapshot</summary>

<img width="1070" alt="Снимок экрана 2023-07-19 в 19 52 22" src="https://github.com/privatenumber/pkg-size.dev/assets/6726016/7d4ffe36-097f-4d2c-b3ff-35f9647e3461">

</details>

**Comment by privatenumber** [comment]
This is happening a result of esbuild creating unused chunks when `splitting` is enabled:
https://github.com/evanw/esbuild/issues/3252

I'm relying on `splitting` as a performance benefit to get the exports and also do the initial build at the same time, so it's difficult to disable right now.

**Comment by privatenumber** [comment]
I disabled `splitting` so you should be able to see accurate results:


<img width="1046" src="https://github.com/privatenumber/pkg-size.dev/assets/1075694/16bd6223-c231-49ea-841a-41fd5d221f7f">
