### ISSUE TITLE
Feature Request: Add functionality for input of package.json file

### ISSUE THREAD

**Issue by realityzero** [privatenumber/pkg-size.dev#11]
**Proposed Solution:**

The proposed solution is to extend the existing CLI with a new command that enables users to input their _package.json_ file. When users execute the new command, the system will read the _package.json_ file, extract relevant package details (e.g., dependencies, devDependencies, scripts, etc.), and automatically populate the project setup with the appropriate dependencies and configurations. This will eliminate the need for manual entry and minimise the chances of errors during setup.

**Benefits:**

- Improved User Experience
- Error Reduction

**Comment by privatenumber** [comment]
Done:

<img width="600" src="https://github.com/privatenumber/pkg-size.dev/assets/1075694/d5463322-7c58-4233-8115-644d4c92a69b">

<img width="600"  src="https://github.com/privatenumber/pkg-size.dev/assets/1075694/a8894fc6-33ad-4cdb-9954-10e513736e8a">

The `scripts` are removed as they usually reference local files which won't be resolvable.
