### ISSUE TITLE
Drop a Tgz / Tarbal

### ISSUE THREAD

**Issue by antfu** [privatenumber/pkg-size.dev#24]
### Feature request

Able to drop and install from a local .tgz file

### Motivations

Sometimes I'd like to verify how much improvements I have made in the local build before publishing. Drop a/mutliple .tgz files from `npm pack` would be very helpful.

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Just deployed this feature! Thanks for the request and hope it works well for you :)

**Comment by antfu** [comment]
Thanks!
