### ISSUE TITLE
Cache results

### ISSUE THREAD

**Issue by lishaduck** [privatenumber/pkg-size.dev#32]
### Feature request

I'd be nice if pkg-size served cached sizes; it seems to store them, given the badges at the bottom of the pages.

### Motivations

I would love to be able to view packages sizes quickly.

### Alternatives

Wait for a webcontainer to boot if I accidentally close a tab. Especially relevant for large packages like ESLint configs.

### Additional context

Semi-related: #22.

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Unfortunately, caching would require a database, and we’d need to move npm install from the browser to the server for data integrity. This means we’ll need to set up a server and secure funding for it, which I don't think I have capacity for.

**Comment by lishaduck** [comment]
The badges had looked like they had ids, but I looked again and realized that they're just the size in bytes. I assumed there was already a server, but as there isn't, I agree that this is doesn't really make sense.

**Comment by styfle** [comment]
See https://github.com/styfle/packagephobia if you want caching

**Comment by lishaduck** [comment]
I used it for a while, but I've found pkg-size to be more in-depth and is stabler.
