### ISSUE TITLE
Question: Minification Size for Different Environments

### ISSUE THREAD

**Issue by jantimon** [privatenumber/pkg-size.dev#5]
Hi there!

I've been wondering about the minification size displayed on the website. As you may know, in a typical development setup, we often have different code sizes for development and production environments.

My question is whether pkg-size.dev takes into account the different minification sizes for code in different environments, specifically by using the `process.env.NODE_ENV === "production"` flag.

e.g. react:

![shot-ZWMuZAUU](https://github.com/privatenumber/pkg-size.dev/assets/4113649/adc71aaa-e57c-4a38-8e1e-98c197246c48)

https://github.com/facebook/react/blob/9f4fbec5f7bb639be6dac438f9da5f032ae12c15/packages/react/npm/index.js#L1-L7

**Comment by privatenumber** [comment]
Good catch, thanks!

I think it makes sense to default to production mode (`process.env.NODE_ENV="production"`).

Just pushed an update.

React now shows the production size:
<img width="1071" src="https://github.com/privatenumber/pkg-size.dev/assets/1075694/2c028cf0-67f4-4775-aba4-44e54cd20f6d">
