### ISSUE TITLE
Feature Request: Display Gzip Size

### ISSUE THREAD

**Issue by jantimon** [privatenumber/pkg-size.dev#6]
Hello 🙃

I have a feature request that I believe would further enhance the usefulness of pkg-size.dev.  
It would be great if the website could display the Gzip size alongside the minification size for the bundle size.

**Comment by privatenumber** [comment]
Done!

<img width="1106" src="https://github.com/privatenumber/pkg-size.dev/assets/1075694/afb705eb-2017-49f4-bbd6-431c9b9216c5">
